version: '3.1'

services:

  db:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
#
#  vault:
#    image: vault
#    ports:
#      - "8200:8200"
#    volumes:
#      - ./data/vault:/vault/file:rw
#      - ./config/vault.json:/vault/config/vault.json:rw
#    cap_add:
#      - IPC_LOCK
#    environment:
#      VAULT_ADDR: http://127.0.0.1:8200
#    entrypoint: vault server -config=/vault/config/vault.json

#  centrifugal:
#    image: centrifugo/centrifugo:v4.1.3
#    command: centrifugo -c config.json --engine=redis --redis_address=redis:6379
#    ports:
#      - "8000:8000"
#    volumes:
#      - "./config.json:/centrifugo/config.json"
#    ulimits:
#      nproc: 65536
#      nofile:
#        soft: 65536
#        hard: 65536

  redis:
    image: redis
    ports:
      - "6379:6379"
