apiVersion: v1
kind: Service
metadata:
  name: {{ include "launchboxhq.fullname" . }}-worker
  labels:
    {{- include "launchboxhq.labels" . | nindent 4 }}
    component: worker
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "launchboxhq.selectorLabels" . | nindent 4 }}
    component: worker
