{{- $labels := include "launchboxhq.labels" . }}
{{- $annotations := .Values.serviceAccount.annotations }}
{{- $name := include "launchboxhq.serviceAccountName" . }}
{{- range .Values.workers }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $name }}-worker-{{ .name }}
  labels:
    {{- $labels | nindent 4 }}
    worker: {{ .name }}
  {{- with $annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
