---
apiVersion: v1
kind: Namespace
metadata:
  name: lbx-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: launchboxhq
  namespace: lbx-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: launchboxhq-dev
subjects:
  - kind: ServiceAccount
    name: launchboxhq
    namespace: lbx-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin