{{- if eq .Values.cloud "digitalocean" }}
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: DOCluster
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  region: {{ .Values.digitalocean.region }}
{{ end }}