{{- if eq .Values.cloud "vcluster" }}
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: VCluster
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  controlPlaneEndpoint:
    host: {{ .Values.vcluster.controlPlaneEndpoint.host }}
    port: {{ .Values.vcluster.controlPlaneEndpoint.port }}
  helmRelease:
    chart:
      name: {{ .Values.vcluster.helmRelease.chart.name }}
      repo: {{ .Values.vcluster.helmRelease.chart.repo }}
      version: {{ .Values.vcluster.helmRelease.chart.version }}
    values: |
      {{ toYaml .Values.vcluster.helmRelease.values }}
  kubernetesVersion: 1.23.3
{{- end }}