# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: app/proto/Agent.proto for package 'launchbox'

require 'grpc'
require 'app/proto/Agent_pb'

module Launchbox
  module Jobs
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'launchbox.Jobs'

      rpc :GetJob, ::Launchbox::GetJobReq, ::Launchbox::GetJobResp
    end

    Stub = Service.rpc_stub_class
  end
end
