# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app/proto/Agent.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("app/proto/Agent.proto", :syntax => :proto3) do
    add_message "launchbox.GetJobReq" do
      optional :id, :uint64, 1
    end
    add_message "launchbox.GetJobResp" do
      optional :id, :uint64, 1
      optional :name, :string, 2
    end
  end
end

module Launchbox
  GetJobReq = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("launchbox.GetJobReq").msgclass
  GetJobResp = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("launchbox.GetJobResp").msgclass
end
