default: &default
  adapter: postgresql
  username: postgres
  host: localhost
  password: password
  database: launchboxhq_test

development:
  <<: *default
  username: postgres
  host: localhost
  password: password
  database: launchboxhq_development

test:
  <<: *default
  username: postgres
  host: localhost
  password: password
  database: launchboxhq_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
