default: &default
  adapter: postgresql
  encoding: unicode
  url: <%= ENV["DATABASE_URL"] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: launchboxhq_development

test:
  <<: *default
  database: launchboxhq_test

production:
  <<: *default
  database: launchboxhq_production
