apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: project.core.launchboxhq.io
spec:
  writeConnectionSecretsToNamespace: crossplane-system
  compositeTypeRef:
    apiVersion: core.launchboxhq.io/v1alpha1
    kind: Project
  resources:
    #################################
    # Create the vcluster environment
    #################################
    - name: vcluster
      base:
        apiVersion: helm.crossplane.io/v1beta1
        kind: Release
        spec:
          forProvider:
            chart:
              name: vcluster
              repository: https://charts.loft.sh
              version: 0.13.0
            namespace: # patched
            values: # patched
#              syncer:
#                extraArgs: []
#              sync:
#                # We don't want to deploy ingress controllers in each cluster
#                ingresses:
#                  enabled: true
#                # Copy serviceaccounts to host cluster. This way we can just use
#                # the generated OIDC for the host cluster, instead of having to
#                # configure IRSA for each vcluster instance
#                serviceaccounts:
#                  enabled: true
#              ingress:
#                enabled: true
#                host: # patched
#                ingressClassName: nginx
#              init:
#                manifests: |-
#              vcluster:
#                extraArgs:
#                  - --kube-apiserver-arg=--oidc-username-claim=preferred_username
#                image: rancher/k3s:v1.24.1-k3s1
#                resources:
#                  limits:
#                    cpu: # patched
#                    memory: # patched
#                  requests:
#                    cpu: # patched
#                    memory: # patched
      patches:
        - fromFieldPath: metadata.name
          toFieldPath: metadata.annotations[crossplane.io/external-name]
          policy:
            fromFieldPath: Required
        - type: FromCompositeFieldPath
          fromFieldPath: metadata.labels[crossplane.io/claim-name]
          toFieldPath: spec.forProvider.namespace
        - type: FromCompositeFieldPath
          fromFieldPath: spec.vcluster.values
          toFieldPath: spec.forProvider.values
        - type: CombineFromComposite
          combine:
            variables:
              - fromFieldPath: metadata.name
              - fromFieldPath: spec.domain
            strategy: string
            string:
              fmt: "%s.%s"
          toFieldPath: status.hostname
    ############
    # Initialize a helm provider that can access the new vcluster
    ############
    - name: helm-provider
      base:
        apiVersion: helm.crossplane.io/v1alpha1
        kind: ProviderConfig
        spec:
          credentials:
            source: Secret
            secretRef:
              name: # patched
              namespace: # patched
              key: config
      patches:
        - fromFieldPath: metadata.name
          toFieldPath: spec.credentials.secretRef.name
          transforms:
            - type: string
              string:
                fmt: vc-%s
        - fromFieldPath: metadata.name
          toFieldPath: spec.credentials.secretRef.namespace
        - fromFieldPath: metadata.name
          toFieldPath: metadata.name
        - fromFieldPath: metadata.name
          toFieldPath: metadata.annotations[crossplane.io/external-name]

    ############
    # Initialize a kubernetes provider as well
    ############
    - name: kubernetes-provider
      base:
        apiVersion: kubernetes.crossplane.io/v1alpha1
        kind: ProviderConfig
        spec:
          credentials:
            source: Secret
            secretRef:
              name: # patched
              namespace: # patched
              key: config
      patches:
        - fromFieldPath: metadata.name
          toFieldPath: spec.credentials.secretRef.name
          transforms:
            - type: string
              string:
                fmt: vc-%s
        - fromFieldPath: metadata.name
          toFieldPath: spec.credentials.secretRef.namespace
        - fromFieldPath: metadata.name
          toFieldPath: metadata.name
        - fromFieldPath: metadata.name
          toFieldPath: metadata.annotations[crossplane.io/external-name]
