---
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: projects.core.launchboxhq.io
spec:
  group: core.launchboxhq.io
  names:
    kind: Project
    plural: projects
  claimNames:
    kind: Cluster
    plural: clusters
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                vcluster:
                  type: object
                  properties:
                    values:
                      type: object
                      # For now, we allow arbitrary values to be passed
                      # to the underlying vcluster helm installation
                      x-kubernetes-preserve-unknown-fields: true
                    chart:
                      type: object
                      properties:
                        name: { type: string }
                        repository: { type: string }
                        url: { type: string }
                        version: { type: string }

