{{- if eq .Values.cloud "google" }}
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: GCPMachineTemplate
metadata:
  name: {{ .Release.Name }}-control-plane
  namespace: {{ .Release.Namespace }}
spec:
  template:
    spec:
      image: {{ .Values.google.controlPlane.image }}
      instanceType: {{ .Values.google.controlPlane.machineType }}
{{- end }}