{{- if ne .Values.cloud "cluster" }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-install-cni
  namespace: {{ .Release.Namespace }}
spec:
  template:
    spec:
      containers:
        - name: doctl
          image: bitnami/kubectl
          command:
            - sh
            - "-c"
            - |
              /bin/bash <<'EOF'

              kubectl apply -f https://raw.githubusercontent.com/projectcalico/calico/v3.24.1/manifests/calico.yaml
              {{- if eq .Values.cloud "digitalocean"}}
              kubectl apply -f https://raw.githubusercontent.com/digitalocean/digitalocean-cloud-controller-manager/master/releases/v0.1.27.yml
              kubectl apply -f https://raw.githubusercontent.com/digitalocean/csi-digitalocean/master/deploy/kubernetes/releases/csi-digitalocean-v1.3.0.yaml
              {{- end }}
              EOF
          env:
          - name: KUBECONFIG
            value: /capi/kubeconfig
          volumeMounts:
            - mountPath: /capi
              name: kubeconfig

      restartPolicy: OnFailure
  # TODO: Mount kubeconfig for cluster access
  # TODO: Mount access token from secret
      volumes:
        - name: kubeconfig
          secret:
            secretName: {{ .Release.Name }}-kubeconfig
            items:
              - key: value
                path: kubeconfig
  backoffLimit: 4

{{- end }}