apiVersion: v2
name: launchboxhq
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "0.0.1"
dependencies:
  - name: postgresql
    version: ~12.1.0
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: ~17.3.8
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: vault
    version: ~0.22.1
    repository: https://helm.releases.hashicorp.com
    condition: vault.enabled
